views:
  engines:
    njk: 'vision-nunjucks'
  path: '{{CWD}}/views'
  defaultExtension: 'njk'
  compileMode: 'async'
  isCached: false

assets:
  path: '{{CWD}}/public'
  dist: '_dist/'
  endpoint: '/ui'
  routeConfig:
    cache:
      privacy: 'public'
      expiresIn: '{{ 1000 * 60 * 60 * 24 * 30 }}'
    cors: true
