name: 'mongo-query'
mongo:
  host: "{{ENV.MONGO_PORT_27017_TCP_ADDR}}"
  port: "{{ENV.MONGO_PORT_27017_TCP_PORT}}"
  username: "{{ENV.MONGO_USERNAME || null}}"
  password: "{{ENV.MONGO_PASSWORD || null}}"
  auth: "{{ ENV.MONGO_USERNAME ? mongo.username+':'+mongo.password+'@' : '' }}"
  url: "mongodb://{{mongo.auth}}{{mongo.host}}:{{mongo.port}}"
